### ISSUE TITLE
WebSocket Disconnection Issue

### ISSUE THREAD

**Issue by JihyeHong** [etherdelta/etherdelta.github.io#227]
Hello,

I am working on C# .Net and developed a new WebSocket client program using SocketIO.
I ran the getMarket endpoint and it works but the connection is frequently disconnected and occasionally get the data.
Sometimes it just pends for hours without timeout or returning exception.
Its current timeout option is 5000 ms. 
When the program works well, it gives the data once a minute which is very slow. 
I wonder if you can provide some guidance on it.

Thank you.

**Comment by suspended** [comment]
You need to send a ping every <60 seconds to keep the socket alive

**Comment by JihyeHong** [comment]
I suppose it was not the problem of the socket request. 
I fixed the issue as adding IO option 'Transport' with a reference below. 
https://github.com/Quobject/SocketIoClientDotNet/issues/40

Thanks.

**Comment by minibbjd** [comment]
How would I ping in node.js with the websocket API? 

I've tried socket.emit("message", order) every 50 seconds, but still see frequent disconnects.

**Comment by zackcoburn** [comment]
What are you using for your connection function?

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by minibbjd** [comment]
I've used your bots takers examples to build on. I'm using:

      self.socket = io.connect(self.config.socketURL, {transports: ["websocket"]});

**Comment by zackcoburn** [comment]
I'm not sure. The socket should stay alive if you use this connection
string.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by yangbod123** [comment]
In fact disconnection often appears in my script using bots takers examples. So I have to reconnect the socket myself.

**Comment by alphasignal** [comment]
Has this been resolved? I am having the same problem from a C++ library.

**Comment by daemonraco** [comment]
+1
